//I2C
OMV_GPIO_DEFINE(B,  8,  AF4, I2C1)  //I2C1_SCL
OMV_GPIO_DEFINE(B,  9,  AF4, I2C1)  //I2C1_SDA
OMV_GPIO_DEFINE(B,  8, NONE, GPIO)
OMV_GPIO_DEFINE(B,  9, NONE, GPIO)
OMV_GPIO_DEFINE(B, 10,  AF4, I2C2)  //I2C2_SCL
OMV_GPIO_DEFINE(B, 11,  AF4, I2C2)  //I2C2_SDA
OMV_GPIO_DEFINE(B, 10, NONE, GPIO)
OMV_GPIO_DEFINE(B, 11, NONE, GPIO)
//SPI
OMV_GPIO_DEFINE(B,  3,  AF6, SPI3)  //SPI3_CLK
OMV_GPIO_DEFINE(B,  4,  AF6, SPI3)  //SPI3_MISO
OMV_GPIO_DEFINE(B,  5,  AF7, SPI3)  //SPI3_MOSI
OMV_GPIO_DEFINE(A, 15,  AF6, SPI3)  //SPI3_NSS
OMV_GPIO_DEFINE(E, 12,  AF5, SPI4)  //SPI4_CLK
OMV_GPIO_DEFINE(E, 13,  AF5, SPI4)  //SPI4_MISO
OMV_GPIO_DEFINE(E, 14,  AF5, SPI4)  //SPI4_MOSI
OMV_GPIO_DEFINE(E, 11,  AF5, SPI4)  //SPI4_NSS
OMV_GPIO_DEFINE(D, 15, NONE, GPIO)  //LCD_BL
OMV_GPIO_DEFINE(E, 15, NONE, GPIO)  //LCD_DC
OMV_GPIO_DEFINE(E, 10, NONE, GPIO)  //LCD_RESET
//DCMI
OMV_GPIO_DEFINE(A,  8,  AF1, TIM1)  //DCMI_CLK
OMV_GPIO_DEFINE(A,  4, AF13, DCMI)  //DCMI_HSYNC
OMV_GPIO_DEFINE(A,  6, AF13, DCMI)  //DCMI_PCLK
OMV_GPIO_DEFINE(B,  7, AF13, DCMI)  //DCMI_VSYNC
OMV_GPIO_DEFINE(C,  6, AF13, DCMI)  //DCMI_D0
OMV_GPIO_DEFINE(C,  7, AF13, DCMI)  //DCMI_D0
OMV_GPIO_DEFINE(E,  0, AF13, DCMI)  //DCMI_D2
OMV_GPIO_DEFINE(E,  1, AF13, DCMI)  //DCMI_D3
OMV_GPIO_DEFINE(E,  4, AF13, DCMI)  //DCMI_D4
OMV_GPIO_DEFINE(D,  3, AF13, DCMI)  //DCMI_D5
OMV_GPIO_DEFINE(E,  5, AF13, DCMI)  //DCMI_D6
OMV_GPIO_DEFINE(E,  6, AF13, DCMI)  //DCMI_D7
OMV_GPIO_DEFINE(A,  7, NONE, GPIO)  //CAMERA_RESET
OMV_GPIO_DEFINE(D, 14, NONE, GPIO)  //CAMERA_PWPD
OMV_GPIO_DEFINE(C,  4, NONE, GPIO)  //CAMERA_FSYNC
//GPIO
OMV_GPIO_DEFINE(E,  7, NONE, GPIO)  //LED_R
OMV_GPIO_DEFINE(E,  8, NONE, GPIO)  //LED_G
OMV_GPIO_DEFINE(E,  9, NONE, GPIO)  //LED_IR
OMV_GPIO_DEFINE(C, 13, NONE, GPIO)  //LED_B
